name: Dynamic Test Coverage Badge 

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=myapp --cov-report=xml

      - name: Generate Coverage Badge
        uses: tj-actions/coverage-badge-py@v1
        with:
          output: "coverage.svg"

      - name: Upload Badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: coverage.svg